version: '2'
services:
  postgres:
    image: interactivesolutions/postgres:latest
    environment:
      POSTGRES_USER: 'vcard'
      POSTGRES_PASSWORD: 'vcard'
      POSTGRES_DATABASE: 'vcard'
    ports:
      - 5432:5432

  mailhog:
    image: mailhog/mailhog:latest
    ports:
      - 1025:1025
      - 1080:1080
